version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#openjdk

      - image:circleci/openjdk:8-jdk-stretch

    working_directory: ~/ws-pessoa
    
    steps:
      # git pull
      - checkout

            
      # Download and cache dependencies
      - restore_cache:
          keys:
          - ws-pessoa-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: ws-pessoa-{{ checksum "pom.xml" }}
        
      # package into a jar
      - run: mvn clean package

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: ws-pessoa
